system: &default_system_config
  device: "cuda:0"
  num_workers: 8


path: &default_path_config
  input: '/opt/ml/input'
  train: '/opt/ml/input/data/train'
  test: '/opt/ml/input/data/eval'
  valid: 
  result: '/opt/ml/output/result'
  model: '/opt/ml/output/model'

  logs: '/opt/ml/output/logs'
  configs: '/opt/ml/output/configs'
  


data: &default_data_config
  valid_ratio: 0.2
  upscaling: False
  train_cutmix: False
  cutmix_kernel: 256
  soften_age: False
  custom_augment:
  preprocess: False
  crop_size:
  resize:
  sampler: 
  batch_size: 32


train: &default_train_config
  lr:
    base: 1.0e-3
    classifier: 0
    scheduler: 
    scheduler_manual:
      active: False
      averaging_few: 3
      divider: 10
      low_limit: 1.0e-8
  weight_decay: 1.0e-4
  betas: [0.9, 0.999]
  momentum: 0.9
  nesterov: False
  criterion: CrossEntropyLoss
  optimizer:
    name: AdamP
  
  num_epochs: 10
  valid_iter_limit: 0
  
  valid_min: 1
  test_min: 1
  save_min: 1

  valid_period: 1
  test_period: 0
  save_period: 1
  plot_period: 5

  valid_min_acc: 0
  test_min_acc: 1
  save_min_acc: 0
  plot_min_acc: 0

  #wandb options
  logger: manual


model: &default_model_config
  arc: EfficientNetWithMultihead-pretrained
  name: dummymodel
  state_path: 

  classifying: all
teacher:
  active: False
  state_path: 
